# Generated by Django 6.0.7 on 2026-09-15 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campo', '0003_alter_asignaciontrabajo_rol'),
        ('common', '0039_alter_activity_entity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadOperativa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('pendiente', 'Pendiente'), ('compromiso', 'Compromiso'), ('seguimiento', 'Seguimiento'), ('solicitud_informacion', 'Solicitud de información'), ('dependencia', 'Dependencia'), ('handoff', 'Handoff'), ('soporte', 'Soporte'), ('correccion', 'Corrección')], default='tarea', max_length=32)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado_operativo', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_gestion', 'En gestión'), ('en_espera', 'En espera'), ('bloqueada', 'Bloqueada'), ('escalada', 'Escalada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=32)),
                ('estado_validacion', models.CharField(choices=[('sin_evaluar', 'Sin evaluar'), ('pendiente', 'Pendiente de validación'), ('aprobable', 'Aprobable'), ('requiere_correccion', 'Requiere corrección'), ('requiere_revision', 'Requiere revisión humana'), ('aprobado', 'Aprobado')], default='sin_evaluar', max_length=32)),
                ('vuelta', models.PositiveIntegerField(default=1, help_text='Presentación a validación. Sube con cada devolución.')),
                ('origen_tipo', models.CharField(blank=True, default='', help_text='case, orden_trabajo, conversacion, solicitud, manual', max_length=64)),
                ('origen_id', models.CharField(blank=True, default='', help_text='Id o número del origen', max_length=128)),
                ('vence_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_bloqueo', models.CharField(blank=True, default='', help_text="Obligatorio cuando el estado es 'bloqueada'. Un bloqueo sin causa no sirve.", max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('depende_de', models.ForeignKey(blank=True, help_text='Esta actividad no puede avanzar hasta que la otra termine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='operaciones.actividadoperativa')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_operativas', to='common.org')),
                ('responsable', models.ForeignKey(blank=True, help_text='Puede estar vacío: una actividad sin responsable es una señal, no un error.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_operativas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_actividad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadTecnico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, default='', help_text='Obligatorio cuando disponible=False: vacaciones, permiso, incapacidad.', max_length=255)),
                ('zona', models.CharField(blank=True, default='', help_text='Zona que cubre en esa franja. Vacío = cualquiera.', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_disponibilidad',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='NovedadOperativa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('ausencia', 'Ausencia'), ('bloqueo', 'Bloqueo'), ('falta_material', 'Falta de material'), ('dependencia', 'Dependencia pendiente'), ('reprogramacion', 'Reprogramación'), ('cambio_de_prioridad', 'Cambio de prioridad'), ('dato_incompleto', 'Dato incompleto'), ('demora_sin_causa_registrada', 'Demora sin causa registrada')], max_length=40)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('programada_anterior', models.DateTimeField(blank=True, null=True)),
                ('programada_nueva', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='operaciones.actividadoperativa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='campo.ordentrabajo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='common.org')),
                ('profile', models.ForeignKey(blank=True, help_text='A quién afecta, cuando aplica (una ausencia, por ejemplo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='common.profile')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_registradas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_novedad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionSemanal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('semana_inicio', models.DateField(help_text='Lunes de la semana que planifica')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=16)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_semanales', to='common.org')),
                ('publicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_publicadas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_programacion_semanal',
                'ordering': ['-semana_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionOrden',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, default='', max_length=128)),
                ('prioridad', models.PositiveSmallIntegerField(default=50, help_text='Menor corre antes. 0 = lo más urgente.')),
                ('secuencia', models.PositiveSmallIntegerField(default=0, help_text='Orden dentro de la jornada. NO es una ruta optimizada: es el orden propuesto.')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('confirmada', 'Confirmada'), ('reprogramada', 'Reprogramada'), ('cancelada', 'Cancelada')], default='planificada', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_programacion', to='campo.ordentrabajo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_programacion', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='operaciones.programacionsemanal')),
            ],
            options={
                'db_table': 'operaciones_programacion_orden',
                'ordering': ['dia', 'secuencia'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo_senal', models.CharField(choices=[('caso_abierto_antiguo', 'Caso abierto antiguo'), ('actividad_vencida', 'Actividad vencida'), ('actividad_sin_responsable', 'Actividad sin responsable'), ('actividad_bloqueada', 'Actividad bloqueada'), ('compromiso_por_vencer', 'Compromiso próximo a vencer'), ('dependencia_pendiente', 'Dependencia pendiente'), ('orden_sin_programar', 'Orden sin programación'), ('orden_con_riesgo_operacional', 'Orden con riesgo operacional')], max_length=48)),
                ('origen_tipo', models.CharField(help_text='case, actividad, orden_trabajo', max_length=64)),
                ('origen_id', models.CharField(max_length=128)),
                ('accion_propuesta', models.CharField(help_text='Qué recomienda, en una línea legible.', max_length=255)),
                ('motivo', models.TextField(help_text='Por qué lo recomienda.')),
                ('evidencia', models.JSONField(default=list)),
                ('prioridad', models.PositiveSmallIntegerField(default=50, help_text='Menor es más urgente.')),
                ('impacto', models.CharField(blank=True, default='', help_text='Qué se ve afectado si no se atiende.', max_length=255)),
                ('nivel_autonomia_requerido', models.PositiveSmallIntegerField(choices=[(0, '0 · Observar'), (1, '1 · Recomendar'), (2, '2 · Coordinar'), (3, '3 · Ejecutar acciones reversibles'), (4, '4 · Acción crítica, siempre humano')], default=1, help_text='Qué nivel HABRIA hecho falta para ejecutarla sola.')),
                ('estado', models.CharField(choices=[('propuesta', 'Propuesta'), ('aceptada', 'Aceptada'), ('modificada', 'Modificada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='propuesta', max_length=16)),
                ('conocimiento_version', models.CharField(blank=True, default='', help_text='Regla o documento que se usó, cuando aplica.', max_length=128)),
                ('expira_en', models.DateTimeField(blank=True, help_text='Una recomendación vieja sobre un caso ya cerrado es ruido.', null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, default='', help_text='Qué decidió el Jefe de Operaciones, y con qué comentario.')),
                ('accion_propuesta_ref', models.CharField(blank=True, default='', help_text='Id en asistente.acciones_propuestas. Vacío en Shadow Mode.', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_ia', to='common.org')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_revisadas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_propuesta_supervisor',
                'ordering': ['prioridad', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actividadoperativa',
            index=models.Index(fields=['org', 'estado_operativo', 'vence_en'], name='operaciones_org_id_b666c2_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadoperativa',
            index=models.Index(fields=['org', 'responsable', 'estado_operativo'], name='operaciones_org_id_7c885f_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadoperativa',
            index=models.Index(fields=['org', 'origen_tipo', 'origen_id'], name='operaciones_org_id_62b885_idx'),
        ),
        migrations.AddConstraint(
            model_name='actividadoperativa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_operativo', 'bloqueada'), _negated=True), models.Q(('motivo_bloqueo', ''), _negated=True), _connector='OR'), name='actividad_bloqueada_exige_motivo'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadtecnico',
            index=models.Index(fields=['org', 'fecha', 'profile'], name='operaciones_org_id_67e4c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadtecnico',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='disponibilidad_franja_valida'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadtecnico',
            constraint=models.CheckConstraint(condition=models.Q(('disponible', True), models.Q(('motivo', ''), _negated=True), _connector='OR'), name='ausencia_exige_motivo'),
        ),
        migrations.AddIndex(
            model_name='novedadoperativa',
            index=models.Index(fields=['org', 'tipo', 'created_at'], name='operaciones_org_id_429d12_idx'),
        ),
        migrations.AddIndex(
            model_name='novedadoperativa',
            index=models.Index(fields=['org', 'orden'], name='operaciones_org_id_a81cdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacionsemanal',
            constraint=models.UniqueConstraint(fields=('org', 'semana_inicio'), name='unique_programacion_semana_por_org'),
        ),
        migrations.AddIndex(
            model_name='programacionorden',
            index=models.Index(fields=['org', 'dia'], name='operaciones_org_id_9f774c_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacionorden',
            constraint=models.UniqueConstraint(fields=('programacion', 'orden'), name='unique_orden_por_programacion'),
        ),
        migrations.AddIndex(
            model_name='propuestasupervisor',
            index=models.Index(fields=['org', 'estado', 'prioridad'], name='operaciones_org_id_ee6786_idx'),
        ),
        migrations.AddIndex(
            model_name='propuestasupervisor',
            index=models.Index(fields=['org', 'tipo_senal', 'origen_id'], name='operaciones_org_id_0608b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='propuestasupervisor',
            constraint=models.CheckConstraint(condition=models.Q(('evidencia__in', [[], {}, None]), _negated=True), name='propuesta_exige_evidencia'),
        ),
    ]
