# Generated by Django 6.0.7 on 2026-09-17 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_m09d'),
        ('operaciones', '0002_rls_operaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestasupervisor',
            name='huella_condicion',
            field=models.CharField(blank=True, default='', help_text='Identidad estable de la condición detectada. Ver supervisor.py.', max_length=64),
        ),
        migrations.AlterField(
            model_name='propuestasupervisor',
            name='tipo_senal',
            field=models.CharField(choices=[('caso_abierto_antiguo', 'Caso abierto antiguo'), ('actividad_vencida', 'Actividad vencida'), ('actividad_sin_responsable', 'Actividad sin responsable'), ('actividad_bloqueada', 'Actividad bloqueada'), ('compromiso_por_vencer', 'Compromiso próximo a vencer'), ('dependencia_pendiente', 'Dependencia pendiente'), ('orden_sin_programar', 'Orden sin programación'), ('orden_con_riesgo_operacional', 'Orden con riesgo operacional'), ('programacion_sin_publicar', 'Programación semanal sin publicar'), ('dato_incompleto', 'Dato incompleto')], max_length=48),
        ),
        migrations.AddIndex(
            model_name='propuestasupervisor',
            index=models.Index(fields=['org', 'tipo_senal', 'origen_tipo', 'origen_id', 'huella_condicion'], name='idx_propuesta_dedup'),
        ),
    ]
