# Generated by Django 6.0.7 on 2026-09-17 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_m09d'),
        ('operaciones', '0003_m09d'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestasupervisor',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Contexto que agrega el revisor y que el sistema no podía saber.'),
        ),
        migrations.AddField(
            model_name='propuestasupervisor',
            name='propuesta_original',
            field=models.JSONField(blank=True, default=dict, help_text='Copia literal de lo que recomendó la IA, antes de la primera modificación humana. Se escribe una vez.'),
        ),
        migrations.AddField(
            model_name='propuestasupervisor',
            name='responsable_sugerido',
            field=models.ForeignKey(blank=True, help_text='A quién propone el REVISOR. La IA nunca escribe aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_sugeridas', to='common.profile'),
        ),
    ]
