# Generated by Django 6.0.7 on 2026-09-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_m09f_gobernanza'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadoperativa',
            name='completado_en',
            field=models.DateTimeField(blank=True, help_text='Cuando se marco completada. Null = todavia no.', null=True),
        ),
        migrations.AddField(
            model_name='actividadoperativa',
            name='validado_en',
            field=models.DateTimeField(blank=True, help_text='Cuando se resolvio su validacion. Null = sin resolver.', null=True),
        ),
    ]
