# Generated by Django 6.0.7 on 2026-09-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_m02_fechas_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestasupervisor',
            name='tipo_senal',
            field=models.CharField(choices=[('caso_abierto_antiguo', 'Caso abierto antiguo'), ('actividad_vencida', 'Actividad vencida'), ('actividad_sin_responsable', 'Actividad sin responsable'), ('actividad_bloqueada', 'Actividad bloqueada'), ('compromiso_por_vencer', 'Compromiso próximo a vencer'), ('dependencia_pendiente', 'Dependencia pendiente'), ('orden_sin_programar', 'Orden sin programación'), ('orden_con_riesgo_operacional', 'Orden con riesgo operacional'), ('programacion_sin_publicar', 'Programación semanal sin publicar'), ('dato_incompleto', 'Dato incompleto'), ('orden_sla_vencido', 'Orden con plazo operativo vencido'), ('orden_sla_por_vencer', 'Orden con plazo operativo por vencer')], max_length=48),
        ),
    ]
