# Generated by Django 6.0.7 on 2026-09-20 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_m05a_lifecycle_incidencia'),
        ('operaciones', '0006_m04a_senales_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadoperativa',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('en_gestion', 'En gestión'), ('resuelta', 'Resuelta')], default='abierta', help_text='Ciclo de vida de la incidencia. Solo cambia con una operación explícita de operaciones/novedades.py.', max_length=16),
        ),
        migrations.AddField(
            model_name='novedadoperativa',
            name='impacto',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='', help_text='Afectación operacional declarada. Vacío = sin declarar.', max_length=16),
        ),
        migrations.AddField(
            model_name='novedadoperativa',
            name='resolucion',
            field=models.TextField(blank=True, default='', help_text='Cómo se resolvió. Obligatoria al resolver: sin explicación no se puede distinguir una causa atendida de una olvidada.'),
        ),
        migrations.AddField(
            model_name='novedadoperativa',
            name='resuelta_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se resolvió. Null mientras no lo esté.', null=True),
        ),
        migrations.AddField(
            model_name='novedadoperativa',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, help_text='Quién la resolvió. Null si se resolvió sin actor identificado (una tarea de sistema, por ejemplo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_resueltas', to='common.profile'),
        ),
        migrations.AlterField(
            model_name='propuestasupervisor',
            name='tipo_senal',
            field=models.CharField(choices=[('caso_abierto_antiguo', 'Caso abierto antiguo'), ('actividad_vencida', 'Actividad vencida'), ('actividad_sin_responsable', 'Actividad sin responsable'), ('actividad_bloqueada', 'Actividad bloqueada'), ('compromiso_por_vencer', 'Compromiso próximo a vencer'), ('dependencia_pendiente', 'Dependencia pendiente'), ('orden_sin_programar', 'Orden sin programación'), ('orden_con_riesgo_operacional', 'Orden con riesgo operacional'), ('programacion_sin_publicar', 'Programación semanal sin publicar'), ('dato_incompleto', 'Dato incompleto'), ('orden_sla_vencido', 'Orden con plazo operativo vencido'), ('orden_sla_por_vencer', 'Orden con plazo operativo por vencer'), ('incidencia_sin_resolver', 'Incidencia operativa sin resolver')], max_length=48),
        ),
    ]
