# Generated by Django 6.0.7 on 2026-09-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_m05a_lifecycle_incidencia'),
        ('operaciones', '0007_m05a_lifecycle_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadoperativa',
            name='escalado_a',
            field=models.ForeignKey(blank=True, help_text='A quién se escaló. Obligatorio al escalar: un escalamiento sin destinatario no llega a nadie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalamientos_recibidos', to='common.profile'),
        ),
        migrations.AddField(
            model_name='actividadoperativa',
            name='escalado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se escaló. Null si nunca se escaló.', null=True),
        ),
        migrations.AddField(
            model_name='actividadoperativa',
            name='nivel_escalamiento',
            field=models.CharField(blank=True, choices=[('nivel_1', 'Nivel 1'), ('nivel_2', 'Nivel 2'), ('nivel_3', 'Nivel 3')], default='', help_text='Ruta de gestión a la que se llevó. NO es gravedad ni culpa: la gravedad operacional vive en NovedadOperativa.impacto.', max_length=16),
        ),
        migrations.AlterField(
            model_name='propuestasupervisor',
            name='tipo_senal',
            field=models.CharField(choices=[('caso_abierto_antiguo', 'Caso abierto antiguo'), ('actividad_vencida', 'Actividad vencida'), ('actividad_sin_responsable', 'Actividad sin responsable'), ('actividad_bloqueada', 'Actividad bloqueada'), ('compromiso_por_vencer', 'Compromiso próximo a vencer'), ('dependencia_pendiente', 'Dependencia pendiente'), ('orden_sin_programar', 'Orden sin programación'), ('orden_con_riesgo_operacional', 'Orden con riesgo operacional'), ('programacion_sin_publicar', 'Programación semanal sin publicar'), ('dato_incompleto', 'Dato incompleto'), ('orden_sla_vencido', 'Orden con plazo operativo vencido'), ('orden_sla_por_vencer', 'Orden con plazo operativo por vencer'), ('incidencia_sin_resolver', 'Incidencia operativa sin resolver'), ('escalamiento_sin_destinatario', 'Escalamiento sin destinatario registrado')], max_length=48),
        ),
    ]
