# Generated by Django 6.0.7 on 2026-10-02 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_m05a_lifecycle_incidencia'),
        ('operaciones', '0009_m09n_caso_desincronizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteEstado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fuente', models.CharField(choices=[('smartolt', 'SmartOLT (red optica)'), ('wisphub', 'WispHub (clientes y tickets del ISP)'), ('dexter', 'Dexter / CRM (casos)'), ('sla', 'SLA (riesgo temporal)'), ('m02', 'M02 (actividades y compromisos)'), ('m03', 'M03 (programacion y ordenes)')], max_length=32)),
                ('activa', models.BooleanField(default=False)),
                ('frecuencia_segundos', models.PositiveIntegerField(default=300)),
                ('antiguedad_maxima_segundos', models.PositiveIntegerField(default=900)),
                ('ventana_inconclusa_segundos', models.PositiveIntegerField(default=0)),
                ('ultima_consulta_inicio', models.DateTimeField(blank=True, null=True)),
                ('ultima_consulta_fin', models.DateTimeField(blank=True, null=True)),
                ('proxima_consulta_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('con_datos', 'Consultada, con registros'), ('sin_registros', 'Consultada, sin registros'), ('no_consultada', 'No consultada'), ('error', 'Error de consulta'), ('no_disponible', 'Fuente no disponible'), ('inconclusa', 'Inconclusa (dentro de la ventana de la fuente)')], default='no_consultada', max_length=32)),
                ('frescura', models.CharField(choices=[('fresca', 'Fresca'), ('vieja', 'Vieja (pasa la antiguedad maxima de la fuente)'), ('desconocida', 'Desconocida (la fuente no fecha su dato)'), ('sin_dato', 'Sin dato que fechar')], default='sin_dato', max_length=16)),
                ('registros', models.IntegerField(blank=True, null=True)),
                ('dato_en', models.DateTimeField(blank=True, null=True)),
                ('error_tecnico', models.TextField(blank=True, default='')),
                ('motivo_no_disponible', models.TextField(blank=True, default='')),
                ('ejecucion_id', models.UUIDField(blank=True, null=True)),
                ('tipo_consulta', models.CharField(blank=True, default='', max_length=64)),
                ('esquema', models.CharField(blank=True, default='', max_length=32)),
                ('fallos_consecutivos', models.PositiveIntegerField(default=0)),
                ('ultimo_exito_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_supervisor', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_fuente_estado',
                'ordering': ['fuente'],
                'indexes': [models.Index(fields=['org', 'activa', 'proxima_consulta_en'], name='operaciones_org_id_5dbd3a_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'fuente'), name='fuente_unica_por_org'), models.CheckConstraint(condition=models.Q(('frecuencia_segundos__gte', 30)), name='fuente_frecuencia_minima'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'error'), _negated=True), models.Q(('error_tecnico', ''), _negated=True), _connector='OR'), name='fuente_error_con_motivo'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'no_disponible'), _negated=True), models.Q(('motivo_no_disponible', ''), _negated=True), _connector='OR'), name='fuente_no_disponible_con_motivo')],
            },
        ),
        migrations.CreateModel(
            name='FuenteSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fuente', models.CharField(choices=[('smartolt', 'SmartOLT (red optica)'), ('wisphub', 'WispHub (clientes y tickets del ISP)'), ('dexter', 'Dexter / CRM (casos)'), ('sla', 'SLA (riesgo temporal)'), ('m02', 'M02 (actividades y compromisos)'), ('m03', 'M03 (programacion y ordenes)')], max_length=32)),
                ('capturado_en', models.DateTimeField()),
                ('dato_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('con_datos', 'Consultada, con registros'), ('sin_registros', 'Consultada, sin registros'), ('no_consultada', 'No consultada'), ('error', 'Error de consulta'), ('no_disponible', 'Fuente no disponible'), ('inconclusa', 'Inconclusa (dentro de la ventana de la fuente)')], max_length=32)),
                ('frescura', models.CharField(choices=[('fresca', 'Fresca'), ('vieja', 'Vieja (pasa la antiguedad maxima de la fuente)'), ('desconocida', 'Desconocida (la fuente no fecha su dato)'), ('sin_dato', 'Sin dato que fechar')], default='sin_dato', max_length=16)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('esquema', models.CharField(max_length=32)),
                ('tipo_consulta', models.CharField(blank=True, default='', max_length=64)),
                ('registros', models.IntegerField(blank=True, null=True)),
                ('error_tecnico', models.TextField(blank=True, default='')),
                ('ejecucion_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_supervisor', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_fuente_snapshot',
                'ordering': ['-capturado_en'],
                'indexes': [models.Index(fields=['org', 'fuente', '-capturado_en'], name='operaciones_org_id_a227f2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('estado', 'error'), _negated=True), models.Q(('error_tecnico', ''), _negated=True), _connector='OR'), name='snapshot_error_con_motivo')],
            },
        ),
    ]
