# Generated by Django 6.0.7 on 2026-10-02 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_m05a_lifecycle_incidencia'),
        ('operaciones', '0010_capa_de_fuentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionOperativa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=16)),
                ('tipo', models.CharField(choices=[('afectacion_pon', 'Posible afectación de un PON'), ('afectacion_olt', 'Posible afectación de una OLT'), ('afectacion_zona', 'Posible afectación de una zona'), ('patron_repetido', 'Patrón repetido'), ('otra', 'Otra')], default='otra', max_length=32)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('detectada', 'Detectada'), ('investigando', 'Investigando'), ('confirmada', 'Confirmada'), ('en_atencion', 'En atención'), ('en_verificacion', 'En verificación'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada'), ('descartada', 'Descartada')], default='detectada', max_length=20)),
                ('riesgo', models.CharField(choices=[('informativo', 'Informativo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='informativo', max_length=16)),
                ('huella', models.CharField(max_length=160)),
                ('detectada_en', models.DateTimeField()),
                ('actualizada_en', models.DateTimeField()),
                ('proxima_revision_en', models.DateTimeField(blank=True, null=True)),
                ('senal_vista_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('fuente_origen', models.CharField(blank=True, default='', max_length=32)),
                ('snapshot_origen_id', models.UUIDField(blank=True, null=True)),
                ('hipotesis', models.TextField(blank=True, default='')),
                ('confianza', models.CharField(choices=[('sin_hipotesis', 'Sin hipotesis'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='sin_hipotesis', max_length=16)),
                ('recomendacion', models.TextField(blank=True, default='')),
                ('evidencia', models.JSONField(blank=True, default=list)),
                ('afectados_contados', models.PositiveIntegerField(default=0)),
                ('verificacion', models.TextField(blank=True, default='')),
                ('verificada_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situaciones_operativas', to='common.org')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situaciones_a_cargo', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_situacion',
                'ordering': ['-detectada_en'],
            },
        ),
        migrations.CreateModel(
            name='SituacionEvento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('detectada', 'Detectada'), ('actualizada', 'Actualizada'), ('evidencia_nueva', 'Evidencia nueva'), ('afectado_nuevo', 'Afectado nuevo'), ('afectado_recuperado', 'Afectado recuperado'), ('ticket_asociado', 'Ticket asociado'), ('cambio_estado', 'Cambio estado'), ('cambio_riesgo', 'Cambio riesgo'), ('hipotesis', 'Hipotesis'), ('recomendacion', 'Recomendacion'), ('verificacion', 'Verificacion'), ('senal_ausente', 'Senal ausente'), ('fuente_inconclusa', 'Fuente inconclusa'), ('descarte', 'Descarte'), ('cierre', 'Cierre'), ('relacion', 'Relacion')], max_length=24)),
                ('resumen', models.CharField(max_length=255)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('ocurrido_en', models.DateTimeField()),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_de_situacion', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacion_eventos', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operaciones.situacionoperativa')),
            ],
            options={
                'db_table': 'operaciones_situacion_evento',
                'ordering': ['ocurrido_en', 'registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='SituacionAfectado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('ont', 'Ont'), ('pon', 'Pon'), ('olt', 'Olt'), ('cliente', 'Cliente'), ('servicio', 'Servicio'), ('ticket', 'Ticket'), ('caso', 'Caso'), ('zona', 'Zona'), ('orden', 'Orden'), ('datos_insuficientes', 'Datos insuficientes')], max_length=24)),
                ('identificador', models.CharField(max_length=160)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=120)),
                ('detectado_en', models.DateTimeField()),
                ('visto_en', models.DateTimeField()),
                ('recuperado_en', models.DateTimeField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, default='', max_length=32)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacion_afectados', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afectados', to='operaciones.situacionoperativa')),
            ],
            options={
                'db_table': 'operaciones_situacion_afectado',
                'ordering': ['tipo', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='SituacionRelacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('coincide', 'Coincide'), ('contiene', 'Contiene'), ('contenida_en', 'Contenida en'), ('duplicada_de', 'Duplicada de'), ('explica', 'Explica')], max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('creada_en', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaciones_de_situacion', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_entrantes', to='operaciones.situacionoperativa')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacion_relaciones', to='common.org')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_salientes', to='operaciones.situacionoperativa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_situacion_relacion',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddIndex(
            model_name='situacionoperativa',
            index=models.Index(fields=['org', 'estado', '-detectada_en'], name='operaciones_org_id_3afcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='situacionoperativa',
            index=models.Index(fields=['org', 'huella'], name='operaciones_org_id_fe54e6_idx'),
        ),
        migrations.AddIndex(
            model_name='situacionoperativa',
            index=models.Index(fields=['org', 'tipo', 'estado'], name='operaciones_org_id_089100_idx'),
        ),
        migrations.AddConstraint(
            model_name='situacionoperativa',
            constraint=models.UniqueConstraint(fields=('org', 'codigo'), name='situacion_codigo_unico_por_org'),
        ),
        migrations.AddConstraint(
            model_name='situacionoperativa',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['detectada', 'investigando', 'confirmada', 'en_atencion', 'en_verificacion'])), fields=('org', 'huella'), name='situacion_viva_unica_por_huella'),
        ),
        migrations.AddConstraint(
            model_name='situacionoperativa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'cerrada'), _negated=True), models.Q(models.Q(('verificacion', ''), _negated=True), ('verificada_en__isnull', False)), _connector='OR'), name='situacion_cierre_con_verificacion'),
        ),
        migrations.AddConstraint(
            model_name='situacionoperativa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'descartada'), _negated=True), models.Q(('descripcion', ''), _negated=True), _connector='OR'), name='situacion_descarte_con_motivo'),
        ),
        migrations.AddConstraint(
            model_name='situacionoperativa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hipotesis', ''), ('confianza', 'sin_hipotesis')), models.Q(models.Q(('hipotesis', ''), _negated=True), models.Q(('confianza', 'sin_hipotesis'), _negated=True)), _connector='OR'), name='situacion_hipotesis_con_confianza'),
        ),
        migrations.AddIndex(
            model_name='situacionevento',
            index=models.Index(fields=['situacion', 'ocurrido_en'], name='operaciones_situaci_9ba631_idx'),
        ),
        migrations.AddIndex(
            model_name='situacionevento',
            index=models.Index(fields=['org', 'tipo', '-ocurrido_en'], name='operaciones_org_id_c94cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='situacionafectado',
            index=models.Index(fields=['org', 'tipo', 'identificador'], name='operaciones_org_id_48be4a_idx'),
        ),
        migrations.AddIndex(
            model_name='situacionafectado',
            index=models.Index(fields=['situacion', 'recuperado_en'], name='operaciones_situaci_286973_idx'),
        ),
        migrations.AddConstraint(
            model_name='situacionafectado',
            constraint=models.UniqueConstraint(fields=('situacion', 'tipo', 'identificador'), name='afectado_unico_en_situacion'),
        ),
        migrations.AddConstraint(
            model_name='situacionafectado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'datos_insuficientes'), _negated=True), ('identificador', 'datos_insuficientes'), _connector='OR'), name='afectado_insuficiente_sin_identificador'),
        ),
        migrations.AddConstraint(
            model_name='situacionrelacion',
            constraint=models.UniqueConstraint(fields=('origen', 'destino', 'tipo'), name='relacion_unica_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='situacionrelacion',
            constraint=models.CheckConstraint(condition=models.Q(('origen', models.F('destino')), _negated=True), name='relacion_no_consigo_misma'),
        ),
        migrations.AddConstraint(
            model_name='situacionrelacion',
            constraint=models.CheckConstraint(condition=models.Q(('motivo', ''), _negated=True), name='relacion_con_motivo'),
        ),
    ]
