# Generated by Django 6.0.7 on 2026-10-03 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_m05a_lifecycle_incidencia'),
        ('operaciones', '0011_situaciones_operativas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recomendacion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('acepto', 'Acepto'), ('rechazo', 'Rechazo'), ('modifico', 'Modifico'), ('pospuso', 'Pospuso'), ('expiro', 'Expiro')], max_length=16)),
                ('decidida_en', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('funciono', 'Funciono'), ('no_funciono', 'No funciono'), ('parcial', 'Parcial'), ('no_se_puede_saber', 'No se puede saber')], default='pendiente', max_length=24)),
                ('resultado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado_evidencia', models.TextField(blank=True, default='')),
                ('correccion', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_de_supervisor', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_supervisor', to='common.org')),
                ('propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_registradas', to='operaciones.propuestasupervisor')),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='operaciones.situacionoperativa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_decision_supervisor',
                'ordering': ['-decidida_en'],
                'indexes': [models.Index(fields=['org', '-decidida_en'], name='operaciones_org_id_202ead_idx'), models.Index(fields=['org', 'tipo', 'resultado'], name='operaciones_org_id_db50bc_idx'), models.Index(fields=['situacion', '-decidida_en'], name='operaciones_situaci_84c66d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('situacion__isnull', False), ('propuesta__isnull', False), _connector='OR'), name='decision_con_objeto'), models.CheckConstraint(condition=models.Q(('tipo', 'expiro'), ('actor__isnull', False), _connector='OR'), name='decision_humana_con_actor'), models.CheckConstraint(condition=models.Q(models.Q(('resultado__in', ['funciono', 'no_funciono', 'parcial']), _negated=True), models.Q(('resultado_evidencia', ''), _negated=True), _connector='OR'), name='decision_resultado_con_evidencia')],
            },
        ),
        migrations.CreateModel(
            name='NivelAutonomia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('nivel_anterior', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cambiado_en', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('criterios', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_de_autonomia', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_autonomia_supervisor', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_nivel_autonomia',
                'ordering': ['-cambiado_en'],
                'indexes': [models.Index(fields=['org', '-cambiado_en'], name='operaciones_org_id_c246c0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nivel__lte', 4)), name='autonomia_nivel_en_rango'), models.CheckConstraint(condition=models.Q(('nivel_anterior__isnull', True), ('nivel_anterior__lte', 4), _connector='OR'), name='autonomia_nivel_anterior_en_rango'), models.CheckConstraint(condition=models.Q(('motivo', ''), _negated=True), name='autonomia_con_motivo'), models.CheckConstraint(condition=models.Q(('criterios', ''), _negated=True), name='autonomia_con_criterios')],
            },
        ),
    ]
