# Generated by Django 6.0.7 on 2026-10-05 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_m05a_lifecycle_incidencia'),
        ('operaciones', '0012_gobierno_y_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=160)),
                ('caso_id', models.CharField(blank=True, default='', max_length=64)),
                ('abierta_en', models.DateTimeField()),
                ('ultimo_mensaje_en', models.DateTimeField()),
                ('archivada', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_con_supervisor', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_supervisor', to='common.org')),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='operaciones.situacionoperativa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_conversacion_supervisor',
                'ordering': ['-ultimo_mensaje_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(choices=[('humano', 'Humano'), ('supervisor', 'Supervisor'), ('herramienta', 'Herramienta'), ('error', 'Error')], max_length=16)),
                ('contenido', models.TextField()),
                ('escrito_en', models.DateTimeField()),
                ('herramientas', models.JSONField(blank=True, default=list)),
                ('contexto_usado', models.JSONField(blank=True, default=dict)),
                ('modelo', models.CharField(blank=True, default='', max_length=64)),
                ('proveedor', models.CharField(blank=True, default='', max_length=32)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='operaciones.conversacionsupervisor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_supervisor', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_mensaje_supervisor',
                'ordering': ['escrito_en', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacionsupervisor',
            index=models.Index(fields=['org', 'actor', '-ultimo_mensaje_en'], name='operaciones_org_id_0ca70c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionsupervisor',
            index=models.Index(fields=['org', 'situacion'], name='operaciones_org_id_4af28f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajesupervisor',
            index=models.Index(fields=['conversacion', 'escrito_en'], name='operaciones_convers_afbd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajesupervisor',
            index=models.Index(fields=['org', '-escrito_en'], name='operaciones_org_id_ee515d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensajesupervisor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rol', 'error'), _negated=True), models.Q(('error', ''), _negated=True), _connector='OR'), name='mensaje_error_con_motivo'),
        ),
    ]
