# Generated by Django 6.0.7 on 2026-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_chat_del_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacionevento',
            name='tipo',
            field=models.CharField(choices=[('detectada', 'Detectada'), ('actualizada', 'Actualizada'), ('evidencia_nueva', 'Evidencia nueva'), ('afectado_nuevo', 'Afectado nuevo'), ('afectado_recuperado', 'Afectado recuperado'), ('ticket_asociado', 'Ticket asociado'), ('cambio_estado', 'Cambio estado'), ('cambio_riesgo', 'Cambio riesgo'), ('hipotesis', 'Hipotesis'), ('recomendacion', 'Recomendacion'), ('verificacion', 'Verificacion'), ('senal_ausente', 'Senal ausente'), ('fuente_inconclusa', 'Fuente inconclusa'), ('descarte', 'Descarte'), ('cierre', 'Cierre'), ('relacion', 'Relacion'), ('coordinacion', 'Coordinacion')], max_length=24),
        ),
    ]
