# Generated by Django 6.0.7 on 2026-10-05 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_p6_coordinacion'),
        ('operaciones', '0014_p6_coordinacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionsupervisor',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_registradas', to='operaciones.propuestasupervisor'),
        ),
        migrations.AlterField(
            model_name='decisionsupervisor',
            name='tipo',
            field=models.CharField(choices=[('acepto', 'Acepto'), ('rechazo', 'Rechazo'), ('modifico', 'Modifico'), ('pospuso', 'Pospuso'), ('expiro', 'Expiro'), ('no_aplicable', 'No_aplicable')], max_length=16),
        ),
        migrations.AlterField(
            model_name='situacionrelacion',
            name='tipo',
            field=models.CharField(choices=[('coincide', 'Coincide'), ('contiene', 'Contiene'), ('contenida_en', 'Contenida en'), ('duplicada_de', 'Duplicada de'), ('explica', 'Explica'), ('reincidencia', 'Reincidencia')], max_length=20),
        ),
        migrations.CreateModel(
            name='AprendizajeSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('recomendacion_confirmada', 'Recomendacion confirmada'), ('rechazo_errado', 'Rechazo errado'), ('falso_positivo', 'Falso positivo'), ('omision', 'Omision'), ('correlacion_correcta', 'Correlacion correcta'), ('correlacion_incorrecta', 'Correlacion incorrecta'), ('reincidencia', 'Reincidencia'), ('correccion_humana', 'Correccion humana')], max_length=32)),
                ('origen', models.CharField(choices=[('persona', 'Persona'), ('verificacion', 'Verificacion'), ('evidencia_operativa', 'Evidencia operativa')], max_length=24)),
                ('conclusion', models.TextField(help_text='Que se aprendio, en una frase que se entienda sola.')),
                ('evidencia', models.TextField(help_text='En que se basa. Sin esto la conclusion es una opinion.')),
                ('confianza', models.CharField(default='media', max_length=16)),
                ('registrado_en', models.DateTimeField()),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprendizajes_registrados', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprendizajes', to='operaciones.decisionsupervisor')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes_supervisor', to='common.org')),
                ('propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprendizajes', to='operaciones.propuestasupervisor')),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='operaciones.situacionoperativa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_aprendizaje_supervisor',
                'ordering': ['-registrado_en'],
                'indexes': [models.Index(fields=['org', 'tipo', 'registrado_en'], name='operaciones_org_id_8cae0e_idx'), models.Index(fields=['org', 'situacion'], name='operaciones_org_id_dd1489_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('situacion__isnull', False), ('propuesta__isnull', False), ('decision__isnull', False), ('tipo', 'omision'), _connector='OR'), name='aprendizaje_con_objeto'), models.CheckConstraint(condition=models.Q(('evidencia', ''), _negated=True), name='aprendizaje_exige_evidencia'), models.CheckConstraint(condition=models.Q(models.Q(('origen', 'persona'), _negated=True), ('actor__isnull', False), _connector='OR'), name='aprendizaje_humano_con_actor')],
            },
        ),
    ]
