# Generated by Django 6.0.7 on 2026-10-07 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_p6_coordinacion'),
        ('operaciones', '0015_p82_desenlace_y_aprendizaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazonamientoSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fuente', models.CharField(choices=[('ciclo', 'Ciclo'), ('chat', 'Chat'), ('seguimiento', 'Seguimiento')], default='ciclo', max_length=16)),
                ('concluyente', models.BooleanField(default=True, help_text='False cuando faltaba informacion, fallo una herramienta o se agotaron las vueltas.')),
                ('hechos', models.JSONField(blank=True, default=list, help_text='Cada hecho con su fuente. Los que no tenian fuente verificada ya fueron descartados antes de llegar aqui.')),
                ('inferencias', models.JSONField(blank=True, default=list)),
                ('riesgos', models.JSONField(blank=True, default=list)),
                ('riesgo', models.CharField(choices=[('informativo', 'Informativo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='informativo', max_length=16)),
                ('hipotesis', models.TextField(blank=True, default='')),
                ('confianza', models.CharField(choices=[('sin_hipotesis', 'Sin hipotesis'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='sin_hipotesis', max_length=16)),
                ('recomendacion', models.TextField(blank=True, default='')),
                ('falta', models.JSONField(blank=True, default=list, help_text='Lo que el cerebro declaro que no pudo averiguar.')),
                ('descartes', models.JSONField(blank=True, default=list, help_text="Lo que 'cerebro.validar()' elimino por no tener respaldo.")),
                ('herramientas', models.JSONField(blank=True, default=list, help_text='Nombres de las herramientas realmente consultadas.')),
                ('vueltas', models.PositiveSmallIntegerField(default=0)),
                ('agotado', models.BooleanField(default=False, help_text='Se quedo sin vueltas antes de cerrar.')),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('proveedor', models.CharField(blank=True, default='', max_length=60)),
                ('duracion_ms', models.PositiveIntegerField(default=0)),
                ('analisis_deterministico', models.JSONField(blank=True, default=dict, help_text='El analisis de la regla ANTES de que el cerebro lo tocara. Si aqui quedara el analisis ya enriquecido, la comparacion seria contra si misma y daria coincidencia siempre.')),
                ('enriquecio', models.BooleanField(default=False, help_text="True solo si el veredicto llego a modificar el analisis. En 'solo registra' es siempre False.")),
                ('registrado_en', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razonamientos_ia', to='common.org')),
                ('propuesta', models.ForeignKey(blank=True, help_text='La propuesta sobre la que razono, si hubo una.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razonamientos', to='operaciones.propuestasupervisor')),
                ('situacion', models.ForeignKey(blank=True, help_text='La situacion analizada, si el razonamiento salio de una.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razonamientos', to='operaciones.situacionoperativa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'razonamiento del cerebro',
                'verbose_name_plural': 'razonamientos del cerebro',
                'db_table': 'operaciones_razonamiento_supervisor',
                'ordering': ['-registrado_en', '-created_at'],
                'indexes': [models.Index(fields=['org', '-registrado_en'], name='operaciones_org_id_0ed0c5_idx'), models.Index(fields=['propuesta', '-registrado_en'], name='operaciones_propues_8f6a3e_idx'), models.Index(fields=['org', 'fuente', '-registrado_en'], name='operaciones_org_id_6fec28_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('confianza', 'sin_hipotesis'), ('hipotesis', '')), models.Q(models.Q(('hipotesis', ''), _negated=True), models.Q(('confianza', 'sin_hipotesis'), _negated=True)), _connector='OR'), name='razonamiento_hipotesis_con_confianza'), models.CheckConstraint(condition=models.Q(('propuesta__isnull', False), ('situacion__isnull', False), _connector='OR'), name='razonamiento_apunta_a_algo')],
            },
        ),
    ]
