# Generated by Django 6.0.7 on 2026-10-07 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_p6_coordinacion'),
        ('operaciones', '0017_rls_razonamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloSupervisor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ambito', models.CharField(choices=[('chat', 'Chat del Supervisor'), ('ciclo', 'Ciclo automatico')], max_length=12)),
                ('texto', models.TextField(help_text='El bloque de estilo que se agrega al nucleo. Tono, largo, que mostrar y que no.')),
                ('texto_anterior', models.TextField(blank=True, default='', help_text='Lo que regia antes de este cambio. Vacio en el primero.')),
                ('cambiado_en', models.DateTimeField()),
                ('motivo', models.TextField(help_text='Por que se cambio. Un prompt sin motivo no se puede discutir despues de que empeore una respuesta.')),
                ('actor', models.ForeignKey(blank=True, help_text="Quien lo cambio. 'estilo.cambiar' lo exige.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estilos_cambiados', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos_supervisor', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'estilo del Supervisor',
                'verbose_name_plural': 'estilos del Supervisor',
                'db_table': 'operaciones_estilo_supervisor',
                'ordering': ['-cambiado_en', '-created_at'],
                'indexes': [models.Index(fields=['org', '-cambiado_en'], name='operaciones_org_id_2e69a3_idx'), models.Index(fields=['org', 'ambito', '-cambiado_en'], name='operaciones_org_id_d4f8d3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('texto', ''), _negated=True), name='estilo_no_vacio'), models.CheckConstraint(condition=models.Q(('motivo', ''), _negated=True), name='estilo_con_motivo')],
            },
        ),
    ]
