# Generated by Django 6.0.7 on 2026-10-08 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_p6_coordinacion'),
        ('operaciones', '0019_rls_estilo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='decisionsupervisor',
            name='decision_humana_con_actor',
        ),
        migrations.AlterField(
            model_name='decisionsupervisor',
            name='tipo',
            field=models.CharField(choices=[('acepto', 'Acepto'), ('rechazo', 'Rechazo'), ('modifico', 'Modifico'), ('pospuso', 'Pospuso'), ('expiro', 'Expiro'), ('no_aplicable', 'No_aplicable'), ('cerro_solo', 'Cerro_solo')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='decisionsupervisor',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['expiro', 'cerro_solo']), ('actor__isnull', False), _connector='OR'), name='decision_humana_con_actor'),
        ),
    ]
