# Generated by Django 6.0.7 on 2026-10-08 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_p6_coordinacion'),
        ('operaciones', '0020_remove_decisionsupervisor_decision_humana_con_actor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaDelegada',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('clave', models.CharField(max_length=64)),
                ('activa', models.BooleanField(default=True)),
                ('pedido_textual', models.CharField(blank=True, default='', max_length=500)),
                ('delegada_en', models.DateTimeField(blank=True, null=True)),
                ('quitada_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delegada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_que_delego', to='common.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_delegadas', to='common.org')),
                ('quitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_que_quito', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'operaciones_tarea_delegada',
                'ordering': ['-delegada_en', '-created_at'],
                'indexes': [models.Index(fields=['org', 'activa'], name='operaciones_org_id_76c071_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'clave'), name='tarea_delegada_unica_por_org'), models.CheckConstraint(condition=models.Q(('activa', False), models.Q(('delegada_por__isnull', False), ('delegada_en__isnull', False)), _connector='OR'), name='tarea_activa_con_quien_y_cuando')],
            },
        ),
    ]
