# Generated by Django 6.0.7 on 2026-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0021_tareadelegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadelegada',
            name='conversacion_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
