# Generated by Django 6.0.7 on 2026-09-09 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_sample'),
        ('cases', '0028_inboundmailbox_webhook_secret_help_text'),
        ('common', '0038_documento_asistente'),
        ('contacts', '0013_contact_is_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='external_created_by',
            field=models.CharField(blank=True, default='', help_text="The provider's 'creado_por' string, verbatim. Identifies an account, not necessarily a person.", max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='external_created_by_type',
            field=models.CharField(blank=True, choices=[('dexter', 'Creado por Dexter'), ('humano_verificado', 'Humano verificado por el proveedor'), ('externo_desconocido', 'Externo, autoria no comprobable')], default='', help_text="Classification of `external_created_by`. 'humano_verificado' only when the provider named an individual account; anything arriving through the shared API-key account that we did not record ourselves is 'externo_desconocido', never 'humano'.", max_length=32),
        ),
        migrations.AddField(
            model_name='case',
            name='external_fetch_error',
            field=models.TextField(blank=True, default='', help_text='Why the last READ/import of this ticket failed, written on the row so it is visible in the platform instead of lost in a log. Never written by an outbound operation.'),
        ),
        migrations.AddField(
            model_name='case',
            name='external_fetched_at',
            field=models.DateTimeField(blank=True, help_text='Last successful READ of this ticket from the provider.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='external_service_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="The provider's own id for the subscription this ticket is about (WispHub 'id_servicio'). It is the bridge to the customer, and from there to the ONU and the OLT, without going through a conversation. Always taken from the provider's payload, never derived from the customer's name.", max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='external_status',
            field=models.CharField(blank=True, default='', help_text="Last status label seen at the provider, verbatim ('Nuevo', 'En Progreso', 'Cerrado'). Deliberately the label and not a translation into `status`: reads come back as labels and writes go out as numeric codes, so storing either one translated would lose which of the two vocabularies this actually is.", max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='external_status_at',
            field=models.DateTimeField(blank=True, help_text='When the provider reported `external_status`.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='external_ticket_id',
            field=models.CharField(blank=True, default='', help_text="Ticket id inside `provider`. Text and not an integer on purpose: it belongs to someone else's numbering and the next ISP may use letters — same reasoning as conversations.ticket_operativo.", max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='provider',
            field=models.CharField(blank=True, default='', help_text="External system this case mirrors, e.g. 'wisphub'. Empty means the case is native to Dexter.", max_length=32),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ticket_id', ''), _negated=True), fields=('org', 'provider', 'external_ticket_id'), name='case_external_ref_unique'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_ticket_id', ''), ('provider', '')), models.Q(models.Q(('provider', ''), _negated=True), models.Q(('external_ticket_id', ''), _negated=True)), _connector='OR'), name='case_external_ref_complete'),
        ),
    ]
