# Generated by Django 6.0.7 on 2026-09-11 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_backfill_ticket_externo'),
        ('common', '0038_documento_asistente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaExterna',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('huella', models.CharField(max_length=64)),
                ('autor_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('autor_usuario', models.CharField(blank=True, default='', max_length=160)),
                ('cuerpo', models.TextField(blank=True, default='')),
                ('creada_en_proveedor', models.DateTimeField(blank=True, null=True)),
                ('archivos', models.PositiveSmallIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_externas', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_externas', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'cases_respuesta_externa',
                'ordering': ['creada_en_proveedor', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('case', 'provider', 'huella'), name='respuesta_externa_unica')],
            },
        ),
    ]
