# Generated by Django 6.0.7 on 2026-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_respuestaexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='external_client_name',
            field=models.CharField(blank=True, default='', help_text='Customer name as reported by `provider`, verbatim. Empty when the provider did not give one -- never composed from other fields. Fallback for display when `account` is null; it is not an identifier and nothing is matched against it.', max_length=255),
        ),
    ]
