# Generated by Django 6.0.7 on 2026-09-08 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0038_documento_asistente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.PositiveIntegerField(help_text='Consecutivo interno por organización')),
                ('origen_sistema', models.CharField(default='manual', help_text='Sistema originador: wisphub, solicitudes, crm, manual', max_length=64)),
                ('origen_tipo', models.CharField(blank=True, default='', help_text='Entidad originadora: ticket, solicitud, case, orden_manual', max_length=64)),
                ('origen_ref', models.CharField(blank=True, default='', help_text='ID o número del origen externo (ej. #91288)', max_length=128)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=64)),
                ('cliente_direccion', models.CharField(max_length=255)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('diagnostico_previo', models.JSONField(blank=True, default=dict, help_text='Diagnóstico previo arrojado por el asistente IA en WhatsApp o SmartOLT')),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Valores de campos técnicos diligenciados en campo (serial_ont, potencia_rx, etc.)')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Control de concurrencia optimista para sincronización offline')),
                ('estado_operativo', models.CharField(choices=[('asignada', 'Asignada'), ('en_camino', 'En camino'), ('en_sitio', 'En sitio'), ('completada_campo', 'Completada en campo'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='asignada', max_length=32)),
                ('estado_validacion', models.CharField(choices=[('sin_evaluar', 'Sin evaluar'), ('pendiente', 'Pendiente de validación'), ('aprobable', 'Aprobable'), ('requiere_correccion', 'Requiere corrección'), ('requiere_revision', 'Requiere revisión humana'), ('aprobado', 'Aprobado')], default='sin_evaluar', max_length=32)),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_campo_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_orden_trabajo',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='EventoTrabajo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(help_text='Ej: orden_creada, tecnico_asignado, trabajo_iniciado, datos_actualizados, etc.', max_length=64)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_campo', to='common.org')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='campo.ordentrabajo')),
            ],
            options={
                'db_table': 'campo_evento_trabajo',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_work_type',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='WorkTypeVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Versión del contrato de interfaz que entiende la aplicación móvil')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('retirada', 'Retirada')], default='borrador', max_length=20)),
                ('esquema', models.JSONField(default=dict, help_text='Pasos, campos técnicos, evidencias requeridas y validaciones deterministas')),
                ('schema_hash', models.CharField(blank=True, default='', max_length=64)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='campo.worktype')),
            ],
            options={
                'db_table': 'campo_work_type_version',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_trabajo_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='campo.worktypeversion'),
        ),
        migrations.CreateModel(
            name='MutacionIdempotente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('http_method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_hash', models.CharField(help_text='SHA256 del cuerpo canónico de la petición', max_length=64)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('respuesta_json', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completada', 'Completada')], default='procesando', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutaciones_idempotentes', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_mutacion_idempotente',
                'constraints': [models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_idempotency_key_per_org')],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaTrabajo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requisito_id', models.CharField(help_text='Identificador del requisito en la versión de plantilla (ej. foto_ont)', max_length=64)),
                ('storage_key', models.CharField(blank=True, default='', max_length=255)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=128)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('estado_archivo', models.CharField(choices=[('pendiente', 'Pendiente'), ('subiendo', 'Subiendo'), ('recibido', 'Recibido'), ('verificado', 'Verificado'), ('fallido', 'Fallido')], default='pendiente', max_length=32)),
                ('capturada_en_cliente', models.DateTimeField(blank=True, help_text='Timestamp del reloj del dispositivo en el momento de la captura', null=True)),
                ('recibida_en_servidor', models.DateTimeField(auto_now_add=True)),
                ('metadatos_captura', models.JSONField(blank=True, default=dict, help_text='Metadatos técnicos: coordenadas GPS del móvil, precisión, modelo, etc.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_campo', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='campo.ordentrabajo')),
            ],
            options={
                'db_table': 'campo_evidencia_trabajo',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('orden_trabajo', 'requisito_id', 'sha256'), name='unique_evidencia_requisito_sha')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTrabajo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(default='tecnico', help_text='Rol en la cuadrilla: tecnico, ayudante, chofer, supervisor', max_length=64)),
                ('es_principal', models.BooleanField(default=False, help_text='Marca si este técnico es el responsable principal de la orden')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_campo', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='campo.ordentrabajo')),
            ],
            options={
                'db_table': 'campo_asignacion_trabajo',
                'ordering': ['-es_principal', 'asignado_en'],
                'constraints': [models.UniqueConstraint(fields=('orden', 'profile'), name='unique_profile_per_orden'), models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('orden',), name='unique_tecnico_principal_por_orden')],
            },
        ),
        migrations.AddConstraint(
            model_name='worktype',
            constraint=models.UniqueConstraint(fields=('org', 'codigo'), name='unique_work_type_codigo_per_org'),
        ),
        migrations.AddConstraint(
            model_name='worktypeversion',
            constraint=models.UniqueConstraint(fields=('work_type', 'version'), name='unique_version_per_work_type'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(fields=('org', 'numero'), name='unique_numero_orden_per_org'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('origen_sistema', 'manual'), _negated=True), fields=('org', 'origen_sistema', 'origen_tipo', 'origen_ref'), name='unique_origen_externo_por_org'),
        ),
    ]
