# Generated by Django 6.0.7 on 2026-09-10 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
        ('common', '0038_documento_asistente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordentrabajo',
            name='unique_origen_externo_por_org',
        ),
        migrations.AddField(
            model_name='evidenciatrabajo',
            name='vuelta',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='contexto',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot tecnico al momento de crear la orden. Historico, no vigente.'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vuelta',
            field=models.PositiveIntegerField(default=1, help_text='Presentacion a validacion. Sube con cada devolucion a correccion.'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado_operativo',
            field=models.CharField(choices=[('asignada', 'Asignada'), ('en_camino', 'En camino'), ('en_sitio', 'En sitio'), ('completada_campo', 'Completada en campo'), ('correccion_requerida', 'Corrección requerida'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='asignada', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('origen_sistema__in', ['manual', 'crm']), _negated=True), fields=('org', 'origen_sistema', 'origen_tipo', 'origen_ref'), name='unique_origen_externo_por_org'),
        ),
    ]
