# Generated by Django 6.0.7 on 2026-09-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_remove_ordentrabajo_unique_origen_externo_por_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='campo.ordentrabajo'),
        ),
    ]
