# Generated by Django 6.0.7 on 2026-09-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_remove_ordentrabajo_unique_origen_externo_por_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontrabajo',
            name='rol',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('tecnico_lider', 'Técnico líder'), ('ayudante', 'Ayudante'), ('chofer', 'Chofer'), ('supervisor', 'Supervisor')], default='tecnico', help_text='Rol en la cuadrilla. Catálogo cerrado, ver ROLES_CUADRILLA.', max_length=64),
        ),
    ]
