# Generated by Django 6.0.7 on 2026-09-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_remove_ordentrabajo_unique_origen_externo_por_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente_detalle_acceso',
            field=models.CharField(blank=True, default='', help_text='Torre, piso, apartamento, portería: cómo se entra.', max_length=255),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente_id_abonado',
            field=models.CharField(blank=True, default='', help_text='Identificador del abonado en el sistema del ISP (ej. WispHub).', max_length=64),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], db_index=True, default='media', help_text='Con qué urgencia se despacha. Ordena la lista del técnico.', max_length=10),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='requisitos_seguridad',
            field=models.JSONField(blank=True, default=list, help_text='Requisitos de seguridad del trabajo. Se informan; no habilitan.'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='resumen',
            field=models.CharField(blank=True, default='', help_text='Qué hay que hacer, en una línea. El tipo de trabajo dice la categoría; esto dice el caso.', max_length=255),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sla_vence_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo vence el compromiso. Lo calcula el backend, no la app.', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ventana_fin',
            field=models.DateTimeField(blank=True, help_text='Fin de la franja comprometida con el cliente.', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ventana_inicio',
            field=models.DateTimeField(blank=True, help_text='Comienzo de la franja comprometida con el cliente.', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='zona',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Zona operativa del trabajo. Agrupa la jornada por cercanía.', max_length=128),
        ),
    ]
