# Generated by Django 6.0.7 on 2026-09-22 16:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_campos_de_despacho'),
        ('common', '0039_alter_securityauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDeKit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('acta', models.CharField(blank=True, default='', max_length=64)),
                ('entregado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado_en', models.DateTimeField(blank=True, help_text='Cuando el tecnico confirmo que recibio lo que dice el acta.', null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_despachados', to='common.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_campo', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_recibidos', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_entrega_kit',
                'ordering': ['-entregado_en'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCatalogo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('clase', models.CharField(choices=[('consumible', 'Consumible'), ('bobina', 'Bobina'), ('serializado', 'Serializado'), ('terminal', 'Terminal')], default='consumible', max_length=20)),
                ('unidad', models.CharField(default='unidades', help_text='Como se cuenta: unidades, m, kg.', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_campo', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_material_catalogo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemDeKit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('serie', models.CharField(blank=True, default='', help_text='Solo para material serializado. Una serie, una unidad.', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campo.entregadekit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='campo.materialcatalogo')),
            ],
            options={
                'db_table': 'campo_item_kit',
            },
        ),
        migrations.CreateModel(
            name='MovimientoDeMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('consumo', 'Consumo'), ('devolucion', 'Devolucion'), ('ajuste', 'Ajuste')], default='consumo', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('serie', models.CharField(blank=True, default='', max_length=128)),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('descuadre', 'Descuadre'), ('conflicto', 'Conflicto')], default='aceptado', max_length=20)),
                ('motivo', models.TextField(blank=True, default='', help_text='Por que quedo en descuadre o conflicto, en palabras.')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('ocurrido_en', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuando paso en la calle, segun el telefono. No es created_at: un movimiento sin senal puede llegar horas despues, y el orden del consumo importa para explicar un saldo.')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='campo.materialcatalogo')),
                ('orden', models.ForeignKey(blank=True, help_text='En que trabajo se uso. Vacio para una devolucion de jornada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_material', to='campo.ordentrabajo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_material', to='common.org')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_material', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_movimiento_material',
                'ordering': ['ocurrido_en', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='entregadekit',
            constraint=models.UniqueConstraint(condition=models.Q(('acta__gt', '')), fields=('org', 'acta'), name='unique_acta_por_org'),
        ),
        migrations.AddConstraint(
            model_name='materialcatalogo',
            constraint=models.UniqueConstraint(fields=('org', 'codigo'), name='unique_material_codigo_por_org'),
        ),
        migrations.AddConstraint(
            model_name='itemdekit',
            constraint=models.UniqueConstraint(condition=models.Q(('serie__gt', '')), fields=('material', 'serie'), name='unique_serie_entregada_por_material'),
        ),
        migrations.AddConstraint(
            model_name='movimientodematerial',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_movimiento_idempotente_por_org'),
        ),
        migrations.AddConstraint(
            model_name='movimientodematerial',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aceptado'), ('serie__gt', ''), ('tipo', 'consumo')), fields=('org', 'material', 'serie'), name='unique_serie_consumida_por_org'),
        ),
    ]
