# Generated by Django 6.0.7 on 2026-09-22 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0004_entregadekit_materialcatalogo_itemdekit_and_more'),
        ('common', '0039_alter_securityauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodematerial',
            name='motivo_tecnico',
            field=models.TextField(blank=True, default='', help_text='Lo que escribio el tecnico al usar mas de lo habitual. Es suyo y no se mezcla con `motivo`, que lo escribe el servidor: cuando hay que reconstruir que paso, importa quien dijo cada cosa.'),
        ),
        migrations.CreateModel(
            name='ReglaDeConsumo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad_habitual', models.DecimalField(blank=True, decimal_places=3, help_text='Lo que se suele usar. Es una referencia, no un limite.', max_digits=12, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=3, help_text='Por encima de esto se avisa fuerte. Vacio: sin tope.', max_digits=12, null=True)),
                ('exige_motivo_sobre_habitual', models.BooleanField(default=False, help_text='Si se pasa de lo habitual, hay que escribir por que.')),
                ('bloquea_sobre_maximo', models.BooleanField(default=False, help_text='La unica opcion que RECHAZA un consumo. Apagada por defecto: el material ya se gasto cuando el telefono lo informa, y rechazarlo borra el registro en vez de devolver el material.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='campo.materialcatalogo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_consumo', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_type', models.ForeignKey(blank=True, help_text='Vacio: vale para cualquier trabajo. Con valor: solo para ese tipo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_consumo', to='campo.worktype')),
            ],
            options={
                'db_table': 'campo_regla_consumo',
                'constraints': [models.UniqueConstraint(fields=('org', 'material', 'work_type'), name='unique_regla_por_material_y_tipo')],
            },
        ),
    ]
