# Generated by Django 6.0.7 on 2026-09-22 17:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0005_movimientodematerial_motivo_tecnico_regladeconsumo'),
        ('common', '0039_alter_securityauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaDeDevolucion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('jornada', models.DateField(default=django.utils.timezone.localdate, help_text='El dia de trabajo que cierra esta acta.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')], default='pendiente', max_length=20)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict, help_text='Los numeros congelados al confirmar. Vacio mientras esta pendiente: hasta entonces se calculan desde los movimientos.')),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_devolucion', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_devolucion', to='common.profile')),
                ('recibida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_recibidas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_acta_devolucion',
                'ordering': ['-jornada'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaDeMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('perdido', 'Perdido'), ('danado', 'Dañado'), ('usado_sin_registrar', 'Utilizado y no registrado'), ('entregado_a_otro', 'Entregado a otro tecnico'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('serie', models.CharField(blank=True, default='', max_length=128)),
                ('motivo', models.TextField(help_text='En palabras. Es lo que alguien va a leer para decidir.')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('ocurrido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='campo.actadedevolucion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evidencia', models.ForeignKey(blank=True, help_text='Preparado para cuando las evidencias se integren con materiales. Hoy no se exige: pedir una foto de algo que se perdio hace seis horas no la hace aparecer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_material', to='campo.evidenciatrabajo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='campo.materialcatalogo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_material', to='common.org')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_material', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_incidencia_material',
                'ordering': ['-ocurrido_en'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDeMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('serie', models.CharField(blank=True, default='', max_length=128)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='common.profile')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='campo.materialcatalogo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_material', to='common.org')),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_transferencia_material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='actadedevolucion',
            constraint=models.UniqueConstraint(fields=('org', 'profile', 'jornada'), name='unique_acta_por_jornada'),
        ),
        migrations.AddConstraint(
            model_name='incidenciadematerial',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_incidencia_idempotente_por_org'),
        ),
        migrations.AddConstraint(
            model_name='transferenciadematerial',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_transferencia_idempotente_por_org'),
        ),
    ]
