# Generated by Django 6.0.7 on 2026-09-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_alter_asignaciontrabajo_rol'),
        ('campo', '0006_actadedevolucion_incidenciadematerial_and_more'),
    ]

    operations = [
    ]
