# Generated by Django 6.0.7 on 2026-09-28 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0007_merge_despacho_y_rol'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontrabajo',
            name='rol',
            field=models.CharField(default='tecnico', help_text='Rol en la cuadrilla: tecnico, ayudante, chofer, supervisor', max_length=64),
        ),
        migrations.AlterField(
            model_name='movimientodematerial',
            name='tipo',
            field=models.CharField(choices=[('consumo', 'Consumo'), ('devolucion', 'Devolucion'), ('ajuste', 'Ajuste'), ('entrada', 'Entrada'), ('despacho', 'Despacho'), ('traslado', 'Traslado'), ('baja', 'Baja')], default='consumo', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivoSerializado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serie', models.CharField(max_length=128)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='campo.materialcatalogo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_serializados', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_activo_serializado',
                'ordering': ['material', 'serie'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionInventario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('bodega', 'Bodega'), ('vehiculo', 'Vehiculo'), ('tecnico', 'Tecnico')], default='bodega', max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_inventario', to='common.org')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_inventario', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_ubicacion_inventario',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionDeActivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posicion', to='campo.activoserializado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posiciones_que_justifica', to='campo.movimientodematerial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_presentes', to='campo.ubicacioninventario')),
            ],
            options={
                'db_table': 'campo_ubicacion_de_activo',
            },
        ),
        migrations.AddField(
            model_name='movimientodematerial',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_de_entrada', to='campo.ubicacioninventario'),
        ),
        migrations.AddField(
            model_name='movimientodematerial',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_de_salida', to='campo.ubicacioninventario'),
        ),
        migrations.AddConstraint(
            model_name='activoserializado',
            constraint=models.UniqueConstraint(fields=('org', 'material', 'serie'), name='unique_activo_serie_por_material'),
        ),
        migrations.AddConstraint(
            model_name='ubicacioninventario',
            constraint=models.UniqueConstraint(fields=('org', 'nombre'), name='unique_ubicacion_nombre_por_org'),
        ),
        migrations.AddConstraint(
            model_name='ubicacioninventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'tecnico')), fields=('org', 'profile'), name='unique_ubicacion_por_tecnico'),
        ),
    ]
