# Generated by Django 6.0.7 on 2026-09-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0008_inventario_ubicaciones_y_activos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemdekit',
            name='unique_serie_entregada_por_material',
        ),
    ]
