# Generated by Django 6.0.7 on 2026-09-28 22:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0009_quitar_unique_serie_de_acta'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodematerial',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referencia', models.CharField(blank=True, default='', help_text='Numero de factura o remision.', max_length=120)),
                ('recibida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('moneda', models.CharField(default='COP', help_text='Una compra tiene UNA moneda. Mezclarlas en un total es el error clasico de una valorizacion.', max_length=8)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='common.org')),
                ('recibida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_recibidas', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_compra',
                'ordering': ['-recibida_en'],
            },
        ),
        migrations.AddField(
            model_name='movimientodematerial',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='campo.compra'),
        ),
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('iniciado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('contado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_hechos', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_inventario', to='common.org')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='campo.ubicacioninventario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_conteo_fisico',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaDeConteo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad_contada', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('existencia_sistema', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('motivo', models.TextField(blank=True, default='', help_text='Por que hay diferencia, en palabras de quien conto.')),
                ('ajuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_de_conteo', to='campo.movimientodematerial')),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='campo.conteofisico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='campo.materialcatalogo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_linea_conteo',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, default='', help_text='NIT, RUT o el que use el pais. Opcional a proposito: hay proveedores chicos sin factura formal.', max_length=64)),
                ('contacto', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Opcional: hay material que entra sin proveedor identificado --una donacion, un traslado entre empresas del grupo--.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='campo.proveedor'),
        ),
        migrations.CreateModel(
            name='ReservaDeMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('serie', models.CharField(blank=True, default='', help_text='Reservar UN aparato concreto. Vacio = reservar cantidad.', max_length=128)),
                ('vence_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('desenlace', models.CharField(blank=True, choices=[('consumida', 'Consumida'), ('liberada', 'Liberada'), ('vencida', 'Vencida')], default='', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='campo.materialcatalogo')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_que_consumio', to='campo.movimientodematerial')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_material', to='campo.ordentrabajo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_material', to='common.org')),
                ('reservada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_hechas', to='common.profile')),
                ('ubicacion', models.ForeignKey(help_text='De donde va a salir. Una reserva es contra UNA bodega.', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='campo.ubicacioninventario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_reserva_material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conteofisico',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'borrador')), fields=('org', 'ubicacion'), name='unique_conteo_abierto_por_ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='lineadeconteo',
            constraint=models.UniqueConstraint(fields=('conteo', 'material'), name='unique_material_por_conteo'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('org', 'nombre'), name='unique_proveedor_por_org'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia__gt', '')), fields=('org', 'proveedor', 'referencia'), name='unique_factura_por_proveedor'),
        ),
        migrations.AddIndex(
            model_name='reservadematerial',
            index=models.Index(condition=models.Q(('resuelta_en__isnull', True)), fields=['ubicacion', 'material'], name='idx_reserva_activa'),
        ),
        migrations.AddConstraint(
            model_name='reservadematerial',
            constraint=models.UniqueConstraint(condition=models.Q(('resuelta_en__isnull', True), ('serie__gt', '')), fields=('org', 'material', 'serie'), name='unique_serie_reservada_activa'),
        ),
    ]
