# Generated by Django 6.0.7 on 2026-09-29 01:47
"""
Repone el catalogo cerrado de 'AsignacionTrabajo.rol'.

POR QUE HACE FALTA, CUANDO '0003' YA LO HABIA CERRADO
-----------------------------------------------------
Porque se volvio a abrir. La secuencia, reconstruida del historial:

  0003_alter_asignaciontrabajo_rol   cierra el catalogo (los cinco choices)
  59cf2a6                            borra 'ROLES_CUADRILLA' del modelo, por
                                     accidente, junto con 474 lineas de
                                     'despacho_views.py' y el resto del modulo
                                     de cuadrilla
  0008_inventario_ubicaciones...     Django la genero desde el modelo YA roto,
                                     asi que propago la perdida a la base:
                                     'rol' quedo sin choices

O sea que el estado final de las migraciones describe un campo abierto, y el
modelo restaurado describe uno cerrado. Esta migracion vuelve a alinearlos.

POR QUE ES 0012 Y NO 0011
-------------------------
Nacio como '0011_restaurar_catalogo_de_rol' colgada de '0010'. Mientras estaba
sin commitear, origin publico '0011_direccion_de_los_movimientos_historicos',
colgada tambien de '0010': dos nodos hoja, y Django se niega a arrancar con
'Conflicting migrations detected'. Como el entrypoint del backend corre
'migrate', eso habria roto el despliegue, no solo las pruebas. Se renumero y se
encadeno detras de la del companero -- no es un merge: no hay dos historias que
unir, era un numero repetido.

QUE NO CAMBIA
-------------
Ningun dato. 'choices' lo valida Django en formularios y serializers, no la
base: no hay CHECK ni tipo enum detras. Las 3 asignaciones de produccion que
dicen 'tecnico_lider' siguen validas porque ese valor esta en el catalogo -- se
incluyo a proposito en 0003 en vez de corregirlo, para no reescribir historico
por una razon cosmetica.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0011_direccion_de_los_movimientos_historicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontrabajo',
            name='rol',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('tecnico_lider', 'Técnico líder'), ('ayudante', 'Ayudante'), ('chofer', 'Chofer'), ('supervisor', 'Supervisor')], default='tecnico', help_text='Rol en la cuadrilla. Catálogo cerrado, ver ROLES_CUADRILLA.', max_length=64),
        ),
    ]
