# Generated by Django 6.0.7 on 2026-09-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0012_plantillas_de_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcatalogo',
            name='imagen_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
