# Generated by Django 6.0.7 on 2026-09-30 03:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0013_materialcatalogo_imagen_key'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado_operativo',
            field=models.CharField(choices=[('asignada', 'Asignada'), ('en_camino', 'En camino'), ('en_sitio', 'En sitio'), ('bloqueada', 'Bloqueada'), ('completada_campo', 'Completada en campo'), ('correccion_requerida', 'Corrección requerida'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='asignada', max_length=32),
        ),
        migrations.CreateModel(
            name='BloqueoDeTrabajo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('abierto_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_operativo_anterior', models.CharField(blank=True, default='', max_length=32)),
                ('detuvo_el_trabajo', models.BooleanField(default=False)),
                ('requiere_noc', models.BooleanField(default=False)),
                ('categoria', models.CharField(blank=True, default='', max_length=64)),
                ('motivo', models.TextField(blank=True, default='')),
                ('necesita', models.TextField(blank=True, default='', help_text='Qué hace falta para poder seguir.')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por_rol', models.CharField(blank=True, choices=[('noc', 'NOC'), ('coordinacion', 'Coordinación'), ('bodega', 'Bodega'), ('tecnico', 'El técnico'), ('cliente', 'El cliente'), ('tercero', 'Un tercero'), ('otro', 'Otro')], default='', max_length=32)),
                ('que_se_hizo', models.TextField(blank=True, default='')),
                ('volvio_a', models.CharField(blank=True, default='', max_length=32)),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_abiertos', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evento_reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueo_abierto', to='campo.eventotrabajo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='campo.ordentrabajo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_de_trabajo', to='common.org')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_resueltos', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_bloqueo_trabajo',
                'ordering': ['-abierto_en'],
                'indexes': [models.Index(fields=['org', 'requiere_noc', 'resuelto_en'], name='idx_bloqueo_noc_abierto')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resuelto_en__isnull', True)), fields=('orden',), name='un_solo_bloqueo_abierto_por_orden')],
            },
        ),
    ]
