# Generated by Django 6.0.7 on 2026-09-30 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0014_bloqueo_de_trabajo'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDeSeguimiento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('minutos_para_reportar', models.PositiveSmallIntegerField(default=30, help_text='Cada cuántos minutos hay que actualizar un trabajo abierto. Sale del procedimiento de la empresa.')),
                ('minutos_contacto_reciente', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Desde cuándo se considera que el teléfono apareció. En nulo, el sistema NO dice «sin sincronización reciente»: no lo puede probar mientras la app no tenga un latido regular.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_seguimiento', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_configuracion_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='ContactoDeDispositivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visto_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_ruta', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_de_dispositivo', to='common.org')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_de_dispositivo', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_contacto_dispositivo',
                'indexes': [models.Index(fields=['org', 'visto_en'], name='idx_contacto_org')],
            },
        ),
    ]
