# Generated by Django 6.0.7 on 2026-10-02 21:01
#
# LA FOTO QUE PERTENECE A UN REPORTE
# ==================================
# Agrega el vinculo `evento` y PARTE la restriccion unica en dos, cada una con su
# alcance. Eso ultimo no es cosmetico:
#
#   Ampliar la original a (orden, requisito, sha, evento) habria APAGADO el
#   deduplicado del checklist. En PostgreSQL NULL no es igual a NULL, asi que dos
#   filas con `evento` vacio, el mismo requisito y el mismo sha256 habrian pasado
#   como distintas -- y la garantia que existia desde el principio se habria
#   perdido sin que ninguna prueba lo dijera.
#
# Por eso: la de siempre se conserva con su mismo nombre, acotada con
# `condition=Q(evento__isnull=True)`, y la evidencia de bitacora recibe la suya.
#
# QUE HAY QUE SABER AL APLICARLA
# ------------------------------
# Entre el RemoveConstraint y el AddConstraint hay un instante SIN indice unico
# sobre el checklist. En un despliegue normal no hay trafico en ese instante --la
# migracion corre antes de que el servidor atienda-- pero conviene saberlo antes
# de aplicarla con la aplicacion viva.
#
# Es aditiva: ninguna fila existente cambia, y las que hay quedan con `evento`
# vacio, que es exactamente lo que son.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0016_unir_inventario_y_catalogo_de_rol'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evidenciatrabajo',
            name='unique_evidencia_requisito_sha',
        ),
        migrations.AddField(
            model_name='evidenciatrabajo',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='El reporte de la bitácora al que pertenece. Vacío = evidencia del checklist.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='campo.eventotrabajo'),
        ),
        migrations.AddConstraint(
            model_name='evidenciatrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', True)), fields=('orden_trabajo', 'requisito_id', 'sha256'), name='unique_evidencia_requisito_sha'),
        ),
        migrations.AddConstraint(
            model_name='evidenciatrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('evento', 'requisito_id', 'sha256'), name='unique_evidencia_evento_sha'),
        ),
    ]
