# Generated by Django 6.0.7 on 2026-10-04 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0017_evidencia_de_un_reporte'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalDeAvisos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chat_webhook', models.URLField(blank=True, default='', help_text='URL del webhook del espacio de Google Chat donde se avisa a la cuadrilla. Vacío: no se publica.', max_length=500)),
                ('url_base_app', models.URLField(blank=True, default='', help_text='Dominio desde el que se arman los enlaces a una orden (https://campo.empresa.co). Sin esto el aviso va sin enlace.', max_length=300)),
                ('activo', models.BooleanField(default=True, help_text='Apagar los avisos sin perder la configuración. Se apaga acá y no borrando el webhook, para que volver a encenderlos no obligue a pedirle la URL otra vez a alguien.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canal_de_avisos', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_canal_de_avisos',
            },
        ),
        migrations.CreateModel(
            name='AvisoEnviado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('clave', models.CharField(help_text='Identifica el HECHO que se avisa, no el intento.', max_length=200)),
                ('canales', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_enviados', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_aviso_enviado',
                'constraints': [models.UniqueConstraint(fields=('org', 'clave'), name='unique_aviso_por_clave')],
            },
        ),
        migrations.CreateModel(
            name='DispositivoDeTecnico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(help_text='El identificador que da el servicio de notificaciones.', max_length=500)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('visto_en', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_campo', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_campo', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_dispositivo_tecnico',
                'constraints': [models.UniqueConstraint(fields=('org', 'token'), name='unique_token_por_org')],
            },
        ),
    ]
