# Generated by Django 6.0.7 on 2026-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0020_alinear_campos_base_de_avisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='contacto_alterno_nombre',
            field=models.CharField(blank=True, default='', help_text='A quién preguntar si el cliente no está: portería, vecino, familiar.', max_length=120),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='contacto_alterno_telefono',
            field=models.CharField(blank=True, default='', help_text='El número del contacto alterno. Se marca de un toque desde la app.', max_length=64),
        ),
        migrations.AlterField(
            model_name='worktypeversion',
            name='schema_version',
            field=models.PositiveIntegerField(default=1, help_text='Version del CONTRATO que entiende la aplicacion movil. NO es el numero de revision de la plantilla: hoy el unico contrato que existe es el 1, y una plantilla nueva sigue hablando el 1.'),
        ),
    ]
