# Generated by Django 6.0.7 on 2026-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0021_contacto_alterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciondeavisos',
            name='telefono_soporte',
            field=models.CharField(blank=True, default='', help_text='A quién llama el técnico desde la app cuando algo no cuadra: el NOC, la mesa de ayuda, el supervisor.', max_length=64),
        ),
    ]
