# Generated by Django 6.0.7 on 2026-10-05 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0022_telefono_de_soporte'),
        ('common', '0041_m05a_lifecycle_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=16)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='campo.materialcatalogo')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_material', to='campo.ordentrabajo')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_material', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_material', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_pedido_de_material',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('org', 'idempotency_key'), name='unique_pedido_idempotente_por_org')],
            },
        ),
    ]
