# Generated by Django 6.0.7 on 2026-10-06 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0023_pedido_de_material'),
        ('common', '0042_p6_coordinacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedidodematerial',
            name='unique_pedido_idempotente_por_org',
        ),
        migrations.AddConstraint(
            model_name='pedidodematerial',
            constraint=models.UniqueConstraint(fields=('org', 'profile', 'idempotency_key'), name='unique_pedido_idempotente_por_persona'),
        ),
    ]
