# Generated by Django 6.0.7 on 2026-10-07 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0024_pedido_idempotente_por_persona'),
        ('common', '0042_p6_coordinacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_que_lidera', to='common.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Ubicacion de inventario de tipo vehiculo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas', to='campo.ubicacioninventario')),
            ],
            options={
                'db_table': 'campo_cuadrilla',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='JornadaDeCuadrilla',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('labor', models.CharField(choices=[('instalacion', 'Instalacion'), ('correctivo', 'Correctivo'), ('trabajos', 'Trabajos')], default='instalacion', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='campo.cuadrilla')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_que_lidero', to='common.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_de_cuadrilla', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_jornada_cuadrilla',
                'ordering': ['-fecha', 'cuadrilla__nombre'],
            },
        ),
        migrations.CreateModel(
            name='IntegranteDeJornada',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes_de_jornada', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_de_cuadrilla', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='campo.jornadadecuadrilla')),
            ],
            options={
                'db_table': 'campo_integrante_jornada',
                'ordering': ['rol', 'profile_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuadrilla',
            constraint=models.UniqueConstraint(fields=('org', 'nombre'), name='unique_cuadrilla_nombre_por_org'),
        ),
        migrations.AddConstraint(
            model_name='jornadadecuadrilla',
            constraint=models.UniqueConstraint(fields=('cuadrilla', 'fecha'), name='unique_jornada_por_cuadrilla_y_dia'),
        ),
        migrations.AddConstraint(
            model_name='integrantedejornada',
            constraint=models.UniqueConstraint(fields=('jornada', 'profile'), name='unique_persona_por_jornada'),
        ),
    ]
