# Generated by Django 6.0.7 on 2026-10-07 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0025_cuadrillas_de_campo'),
        ('common', '0042_p6_coordinacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaOperativa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_operativas', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_zona_operativa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AliasDeZona',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('localidad', models.CharField(db_index=True, max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_de_zona', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='campo.zonaoperativa')),
            ],
            options={
                'db_table': 'campo_alias_de_zona',
                'ordering': ['localidad'],
            },
        ),
        migrations.AddField(
            model_name='jornadadecuadrilla',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='jornadas', to='campo.zonaoperativa'),
        ),
        migrations.AddConstraint(
            model_name='zonaoperativa',
            constraint=models.UniqueConstraint(fields=('org', 'nombre'), name='unique_zona_nombre_por_org'),
        ),
        migrations.AddConstraint(
            model_name='aliasdezona',
            constraint=models.UniqueConstraint(fields=('org', 'localidad'), name='unique_localidad_en_una_sola_zona'),
        ),
    ]
