# Generated by Django 6.0.7 on 2026-10-08 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0027_personas_de_campo'),
        ('common', '0042_p6_coordinacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='labor_habitual',
            field=models.CharField(choices=[('instalacion', 'Instalacion'), ('correctivo', 'Correctivo'), ('trabajos', 'Trabajos')], default='instalacion', max_length=20),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='tope_diario',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='zonas_habituales',
            field=models.ManyToManyField(blank=True, related_name='cuadrillas_habituales', to='campo.zonaoperativa'),
        ),
        migrations.CreateModel(
            name='ConfiguracionDeReparto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('hora_local', models.PositiveSmallIntegerField(default=3)),
                ('tope_por_cuadrilla', models.PositiveSmallIntegerField(default=8)),
                ('copia_la_jornada', models.BooleanField(default=True)),
                ('ultima_corrida', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_de_reparto', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'campo_configuracion_reparto',
            },
        ),
    ]
