# Generated by Django 6.0.7 on 2026-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0028_reparto_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='labor',
            field=models.CharField(blank=True, choices=[('instalacion', 'Instalacion'), ('correctivo', 'Correctivo'), ('trabajos', 'Trabajos')], default='', help_text='Que cuadrillas pueden tomarlo. Vacio = sin clasificar.', max_length=20),
        ),
    ]
