# Generated by Django 6.0.7 on 2026-08-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_org_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='corpus_document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='estado_ingesta',
            field=models.CharField(blank=True, choices=[('pendiente', 'pendiente'), ('procesando', 'procesando'), ('ok', 'ok'), ('error', 'error')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='ingesta_actualizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ingesta_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ingesta_fragmentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='roles_asistente',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='usar_en_asistente',
            field=models.BooleanField(default=False),
        ),
    ]
