# Generated by Django 6.0.7 on 2026-09-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_alter_activity_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SUPERVISOR', 'SUPERVISOR'), ('OPERACIONES', 'OPERACIONES'), ('USER', 'USER')], default='USER', max_length=50),
        ),
    ]
