# Generated by Django 6.0.7 on 2026-09-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_m09d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='entity_type',
            field=models.CharField(choices=[('Account', 'Account'), ('Lead', 'Lead'), ('Contact', 'Contact'), ('Opportunity', 'Opportunity'), ('Case', 'Case'), ('Task', 'Task'), ('Invoice', 'Invoice'), ('Event', 'Event'), ('Document', 'Document'), ('Team', 'Team'), ('ActividadOperativa', 'Actividad operativa'), ('PropuestaSupervisor', 'Propuesta del Supervisor NOC IA'), ('NovedadOperativa', 'Novedad / incidencia operativa')], max_length=50),
        ),
    ]
