# Generated by Django 6.0.7 on 2026-09-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_alter_securityauditlog_event_type'),
        ('common', '0041_m05a_lifecycle_incidencia'),
    ]

    operations = [
    ]
