# Generated by Django 6.0.7 on 2026-08-27 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0038_documento_asistente'),
        ('leads', '0016_alter_leadpipeline_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expira_en', models.DateTimeField()),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('apellido', models.CharField(blank=True, default='', max_length=120)),
                ('edad', models.CharField(blank=True, default='', max_length=16)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=32)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_solicitud', models.CharField(blank=True, default='', max_length=64)),
                ('plan_interesado', models.CharField(blank=True, default='', max_length=160)),
                ('fecha_corte', models.CharField(blank=True, default='', max_length=32)),
                ('como_se_entero', models.CharField(blank=True, default='', max_length=120)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('barrio', models.CharField(blank=True, default='', max_length=160)),
                ('gps_lat', models.CharField(blank=True, default='', max_length=32)),
                ('gps_lng', models.CharField(blank=True, default='', max_length=32)),
                ('gps_precision_m', models.CharField(blank=True, default='', max_length=32)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='solicitudes/%Y/%m/')),
                ('autoriza_centrales_riesgo', models.BooleanField(default=False)),
                ('autoriza_habeas_data', models.BooleanField(default=False)),
                ('texto_autorizaciones', models.TextField(blank=True, default='')),
                ('autorizaciones_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('enviada', 'Enviada')], default='nueva', max_length=16)),
                ('abierta_en', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('ticket_wisphub', models.CharField(blank=True, default='', max_length=64)),
                ('correo_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('fallo_integracion', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_servicio', to='leads.lead')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_servicio', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'solicitudes_solicitudservicio',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', 'estado'], name='solicitudes_org_id_08632c_idx'), models.Index(fields=['org', '-created_at'], name='solicitudes_org_id_ff580c_idx')],
            },
        ),
    ]
