# Generated by Django 6.0.7 on 2026-08-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_documento_asistente'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='nota_revision',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='revisada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to='common.profile'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('sin_factibilidad', 'Sin factibilidad')], default='nueva', max_length=20),
        ),
    ]
