# Generated by Django 6.0.7 on 2026-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitudservicio_nota_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='ip_autorizaciones',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
